<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Six (Regular Expressions)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#regexp</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>re_strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\\)\'</string>
					<key>end</key>
					<string>(?&lt;=\\\\)\'|(?&lt;!\\)\'</string>
					<key>name</key>
					<string>string.literal.perl6fe</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\\)‘</string>
					<key>end</key>
					<string>(?&lt;=\\\\)\’|(?&lt;!\\)’</string>
					<key>name</key>
					<string>string.literal.perl6fe</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.perl6fe#q_left_single_right_single_string_content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\\)\"</string>
					<key>end</key>
					<string>(?&lt;=\\\\)\"|(?&lt;!\\)\"</string>
					<key>name</key>
					<string>string.literal.perl6fe</string>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[\t]+)?(?=#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.perl6fe</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.perl6fe</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.perl6fe</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#re_strings</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[dDhHnNsStTvVwW]</string>
					<key>name</key>
					<string>constant.character.escape.class.regexp.perl6fe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:\w+</string>
					<key>name</key>
					<string>entity.name.section.adverb.perl6fe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\^\^|(?&lt;!\.)\^(?!\.)|\$\$|\$(?!\d|&lt;)|&lt;&lt;|&gt;&gt;</string>
					<key>name</key>
					<string>entity.name.section.boundary.regexp.perl6fe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\)\$\d</string>
					<key>name</key>
					<string>keyword.other.special-method.match.variable.numbered.perlt6e</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.identifier.sigil.regexp.perl6</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.class.match.name.delimiter.regexp.perl6fe</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.identifier.regexp.perl6</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.class.match.name.delimiter.regexp.perl6fe</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.match.assignment.regexp.perl6fe</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)(\&lt;)(\w+)(\&gt;)\s*(=)</string>
					<key>name</key>
					<string>meta.match.variable.perl6fe</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\&lt;(?:\?|\!)\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.perl6fe</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\}\&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.perl6fe</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.interpolation.perl6fe</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.perl6fe</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\(|\)&gt;</string>
					<key>name</key>
					<string>keyword.operator.capture.marker.regexp.perl6fe</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!\\)&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.property.regexp.perl6fe</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.delimiter.property.regexp.perl6fe</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.property.regexp.perl6fe</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#re_strings</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\?|\!)(before|after)\s+</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.negativity.perl6fe</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.section.assertion.perl6fe</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=&gt;)</string>
							<key>name</key>
							<string>meta.assertion.lookaround.perl6fe</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#regexp</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.capturename.perl6fe</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.capture.assignment.perl6fe</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w+)(=)</string>
							<key>name</key>
							<string>meta.capture.assignment.perl6fe</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.property.regexp.perl6fe</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.identifier.property.regexp.perl6fe</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(:)(\w+)</string>
							<key>name</key>
							<string>meta.property.name.regexp.perl6fe</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[+|&amp;\-^]</string>
							<key>name</key>
							<string>keyword.operator.property.regexp.perl6fe</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.charclass.open.regexp.perl6fe</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>constant.character.custom.property.regexp.perl6fe</string>
							<key>end</key>
							<string>\]</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.charclass.close.regexp.perl6fe</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.perl6fe#hex_escapes</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(?&lt;!\\)\\\]</string>
									<key>name</key>
									<string>constant.character.custom.property.regexp.perl6fe</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\.\w+\b</string>
							<key>name</key>
							<string>comment.suppressed.capture.property.regexp.perl6fe</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b\w+\b</string>
							<key>name</key>
							<string>variable.other.identifier.regexname.perl6fe</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\w)\(</string>
							<key>end</key>
							<string>\)</string>
							<key>name</key>
							<string>meta.rule.signature.perl6fe</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.perl6fe</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.\.)\*</string>
					<key>name</key>
					<string>variable.other.identifier.whatever.regexp.perl6fe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\*\*|\*|\?|%|\.\.|\.|(?&lt;=\.\.|\s|\d)\^</string>
					<key>name</key>
					<string>keyword.operator.quantifiers.regexp.perl6fe</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\)\|{1,2}</string>
					<key>name</key>
					<string>support.function.alternation.regexp.perl6fe</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.regexp.perl6fe</string>
	<key>uuid</key>
	<string>588B3FE3-7D1A-413C-9AB9-A44B1EB2B184</string>
</dict>
</plist>
